name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby 2.6.x
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-4.2.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-4.2.x.sprockets-4.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-5.0.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-5.0.x.sprockets-4.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-5.1.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-5.1.x.sprockets-4.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-5.2.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-5.2.x.sprockets-4.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-6.0.x.sprockets-4.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          # Ruby 2.7.x
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.0.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.0.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.1.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.1.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.2.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.2.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-6.0.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-7.0.x.sprockets-4.x"
          # Ruby 3.0.x
          - ruby: '3.0'
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: '3.0'
            gemfile: "gemfiles/Gemfile.rails-7.0.x.sprockets-4.x"
          - ruby: '3.0'
            gemfile: "gemfiles/Gemfile.rails-7.1.x.sprockets-4.x"
          # Ruby 3.1.x
          - ruby: 3.1
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: 3.1
            gemfile: "gemfiles/Gemfile.rails-7.0.x.sprockets-4.x"
          - ruby: 3.1
            gemfile: "gemfiles/Gemfile.rails-7.1.x.sprockets-4.x"
          # Ruby 3.2.x
          - ruby: 3.2
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: 3.2
            gemfile: "gemfiles/Gemfile.rails-7.0.x.sprockets-4.x"
          - ruby: 3.2
            gemfile: "gemfiles/Gemfile.rails-7.1.x.sprockets-4.x"
          # Ruby 3.3.x
          - ruby: 3.3
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: 3.3
            gemfile: "gemfiles/Gemfile.rails-7.0.x.sprockets-4.x"
          - ruby: 3.3
            gemfile: Gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec spec
      - name: Run rubocop
        run: bundle exec rubocop
